/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.appeducore;

import Clases.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    private static ArrayList<Estudiante> estudiantes = new ArrayList<>();
    private static ArrayList<Profesor> profesores = new ArrayList<>();
    Director director = new Director(3001, "Jhonny Rivera", "3001", "Director");

    public static ArrayList<Estudiante> getEstudiantes() {
        return estudiantes;
    }

    public static ArrayList<Profesor> getProfesores() {
        return profesores;
    }

    
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDocumento = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtDocumento.addActionListener(this::txtDocumentoActionPerformed);

        txtContraseña.setActionCommand("<Not Set>");
        txtContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.addActionListener(this::btnIniciarSesionActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDocumento)
                                .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnIniciarSesion)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnIniciarSesion)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        txtContraseña.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed

        int documento = Integer.parseInt(txtDocumento.getText());
        String contraseña = txtContraseña.getText();
       
        
        for(Estudiante est : estudiantes){
            if(est.login(documento, contraseña) == true){
                // Login exitoso como estudiante
                JOptionPane.showMessageDialog(this,
                        "Bienvenido estudiante: " + est.getNombre(),
                        "Acceso concedido",
                        JOptionPane.INFORMATION_MESSAGE);
                // Abrir ventana de menú para estudiante y cerrar login
                new IntfEstudiante(est).setVisible(true);
                dispose(); // Cierra la ventana de login
                return;
            }
        }
        
        for (Estudiante est : estudiantes) {
    est.agregarTarea(new Tarea("Matemáticas", "Resolver ejercicios página 10", "2025-05-20"));
    est.agregarTarea(new Tarea("Lenguaje", "Leer capítulo 3", "2025-05-18"));
    // etc.
}
        
        for(Profesor prof : profesores){
            if(prof.login(documento, contraseña) == true){
                // Login exitoso como estudiante
                JOptionPane.showMessageDialog(this,
                        "Bienvenido Profesor: " + prof.getNombre(),
                        "Acceso concedido",
                        JOptionPane.INFORMATION_MESSAGE);
                // Abrir ventana de menú para estudiante y cerrar login
                new IntfProfesor(prof).setVisible(true);
                dispose();
                return;
            }
        }
        
        if(director.login(documento, contraseña) == true){
              // Login exitoso como estudiante
                JOptionPane.showMessageDialog(this,
                        "Bienvenido Director: " + director.getNombre(),
                        "Acceso concedido",
                        JOptionPane.INFORMATION_MESSAGE);
                // Abrir ventana de menú para estudiante y cerrar login
                new IntfDirector().setVisible(true);
                dispose();
                return;
        }
        
               JOptionPane.showMessageDialog(null,
    "Documento o contraseña incorrectos.",
    "Error de autenticación",
    JOptionPane.ERROR_MESSAGE);
               
               
               
        
        
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
    
        
        profesores.add(new Profesor(new Materia("Matemáticas"), 2001, "Carlos Lopez", "2001", "Profesor"));
        profesores.add(new Profesor(new Materia("Lenguaje"), 2002, "Ana Martinez", "123","Profesor"));
        profesores.add(new Profesor(new Materia("Física"), 2003, "Luis Gomez", "123","Profesor"));
        profesores.add(new Profesor(new Materia("Química"), 2004, "Maria Torres", "123","Profesor"));
        profesores.add(new Profesor(new Materia("Inglés"), 2005, "Jorge Ramirez", "123","Profesor"));

        estudiantes.add(new Estudiante("10A", 1001, "Juan Perez", "1001", "Estudiante"));
        estudiantes.add(new Estudiante("10A", 1002, "Maria Gomez", "1002", "Estudiante"));
        estudiantes.add(new Estudiante("10A", 1003, "Carlos Ruiz", "1003", "Estudiante"));
        estudiantes.add(new Estudiante("10A", 1004, "Ana Torres", "1004", "Estudiante"));
        estudiantes.add(new Estudiante("10A", 1005, "Luis Martinez", "1005", "Estudiante"));

        estudiantes.add(new Estudiante("10B", 1006, "Sofia Ramirez", "1006", "Estudiante"));
        estudiantes.add(new Estudiante("10B", 1007, "Diego Castro", "1007", "Estudiante"));
        estudiantes.add(new Estudiante("10B", 1008, "Valentina Rojas", "1008", "Estudiante"));
        estudiantes.add(new Estudiante("10B", 1009, "Andres Morales", "1009", "Estudiante"));
        estudiantes.add(new Estudiante("10B", 1010, "Laura Herrera", "1010", "Estudiante"));

        estudiantes.add(new Estudiante("11A", 1011, "Sebastian Vargas", "1011", "Estudiante"));
        estudiantes.add(new Estudiante("11A", 1012, "Camila Silva", "1012", "Estudiante"));
        estudiantes.add(new Estudiante("11A", 1013, "Daniel Ortiz", "1013", "Estudiante"));
        estudiantes.add(new Estudiante("11A", 1014, "Paula Mendoza", "1014", "Estudiante"));
        estudiantes.add(new Estudiante("11A", 1015, "Mateo Castillo", "1015", "Estudiante"));
      
        for (Estudiante est : estudiantes) {
            est.agregarTarea(new Tarea("Matemáticas", "Resolver ejercicios", "2025-05-20", true, 8.5));
            est.agregarTarea(new Tarea("Lenguaje", "Leer capítulo 3", "2025-05-18", false, 0));
            est.agregarTarea(new Tarea("Ciencias", "Resumen sistema solar", "2025-05-22", true, 9.0));
            
            
}
        
        
        
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtDocumento;
    // End of variables declaration//GEN-END:variables
}
